In [52]:
import pandas as pd
import numpy as np
df=pd.read_csv("IRIS.csv")
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [53]:
df.index

RangeIndex(start=0, stop=150, step=1)

In [54]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='str')

In [55]:
df.shape

(150, 5)

In [56]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species             str
dtype: object

In [57]:
df.columns.values

<ArrowStringArray>
['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
Length: 5, dtype: str

In [58]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [59]:
df['sepal_length']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [60]:
df.iloc[:10,:1]

   sepal_length
0           5.1
1           4.9
2           4.7
3           4.6
4           5.0
5           5.4
6           4.6
7           5.0
8           4.4
9           4.9

In [61]:
df.isnull().any()

sepal_length    False
sepal_width     False
petal_length    False
petal_width     False
species         False
dtype: bool

In [62]:
df.sepal_length.isnull().sum()

np.int64(0)

In [63]:
df['petal_length']=df['petal_length'].astype("int")
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length      int64
petal_width     float64
species             str
dtype: object

In [64]:
#%pip install scikit-learn
from sklearn import preprocessing
df.head()
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5             1          0.2  Iris-setosa
1           4.9          3.0             1          0.2  Iris-setosa
2           4.7          3.2             1          0.2  Iris-setosa
3           4.6          3.1             1          0.2  Iris-setosa
4           5.0          3.6             1          0.2  Iris-setosa

In [65]:
min_max_scaler=preprocessing.MinMaxScaler()
# min_max_scaler = preprocessing.MinMaxScaler()
x=df.iloc[:,:4]
x_scaled = min_max_scaler.fit_transform(x)
df_normalized = pd.DataFrame(x_scaled)
df_normalized

            0         1    2         3
0    0.222222  0.625000  0.0  0.041667
1    0.166667  0.416667  0.0  0.041667
2    0.111111  0.500000  0.0  0.041667
3    0.083333  0.458333  0.0  0.041667
4    0.194444  0.666667  0.0  0.041667
..        ...       ...  ...       ...
145  0.666667  0.416667  0.8  0.916667
146  0.555556  0.208333  0.8  0.750000
147  0.611111  0.416667  0.8  0.791667
148  0.527778  0.583333  0.8  0.916667
149  0.444444  0.416667  0.8  0.708333

[150 rows x 4 columns]

In [66]:
df['species'].unique()

<ArrowStringArray>
['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
Length: 3, dtype: str

In [67]:
label_encoder = preprocessing.LabelEncoder()
df['species']= label_encoder.fit_transform(df['species'])
df['species'].unique()
df

     sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5             1          0.2        0
1             4.9          3.0             1          0.2        0
2             4.7          3.2             1          0.2        0
3             4.6          3.1             1          0.2        0
4             5.0          3.6             1          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0             5          2.3        2
146           6.3          2.5             5          1.9        2
147           6.5          3.0             5          2.0        2
148           6.2          3.4             5          2.3        2
149           5.9          3.0             5          1.8        2

[150 rows x 5 columns]

In [68]:
species = df[['species']]

# Initialize the OneHotEncoder
encoder = preprocessing.OneHotEncoder()

# Fit and transform the 'species' column
encoded_species = encoder.fit_transform(species).toarray()

# Create a DataFrame with the encoded species
encoded_df = pd.DataFrame(encoded_species, columns=encoder.categories_[0])

# Concatenate the encoded species DataFrame with the original DataFrame
df_encoded = pd.concat([df, encoded_df], axis=1)

# Display the encoded DataFrame
print(df_encoded.head())
encoded_species
encoded_df
df_encoded

   sepal_length  sepal_width  petal_length  petal_width  species    0    1  \
0           5.1          3.5             1          0.2        0  1.0  0.0
1           4.9          3.0             1          0.2        0  1.0  0.0
2           4.7          3.2             1          0.2        0  1.0  0.0
3           4.6          3.1             1          0.2        0  1.0  0.0
4           5.0          3.6             1          0.2        0  1.0  0.0

     2
0  0.0
1  0.0
2  0.0
3  0.0
4  0.0

,sepal_length,sepal_width,petal_length,petal_width,species,0,1,2
0,5.1,3.5,1,0.2,0,1.0,0.0,0.0
1,4.9,3.0,1,0.2,0,1.0,0.0,0.0
2,4.7,3.2,1,0.2,0,1.0,0.0,0.0
3,4.6,3.1,1,0.2,0,1.0,0.0,0.0
4,5.0,3.6,1,0.2,0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...
145,6.7,3.0,5,2.3,2,0.0,0.0,1.0
146,6.3,2.5,5,1.9,2,0.0,0.0,1.0
147,6.5,3.0,5,2.0,2,0.0,0.0,1.0
148,6.2,3.4,5,2.3,2,0.0,0.0,1.0
149,5.9,3.0,5,1.8,2,0.0,0.0,1.0